const express = require('express')
const router = express.Router()
const { getAllRooms } = require('./getAllRooms')
const { getAllEvents } = require('./getAllEvents')
const userEvents = require('./userHome')
const { login } = require('./login')
const addEvent = require('./addEvent')
const { authontication } = require('../middlewares/authontication')
const errors = require('./errors')
const searchAvailableRooms = require('./getAvailableRooms')
const { checkUser } = require('./checkUser')
const editEvent = require('./editEvent.js')
const deleteEvent = require('./deleteEvent')

router.get('/api/check', authontication, checkUser)
router.get('/api/rooms', getAllRooms)
router.get('/api/user-events/:id', userEvents)
router.post('/api/update-event', editEvent)
router.get('/api/events', getAllEvents)
router.get('/api/available-rooms', searchAvailableRooms)
router.post('/api/login', login)
router.post('/api/booking', addEvent)
router.delete('/api/delete-event/:id', deleteEvent)
router.use(errors.serverErr)
router.use(errors.notFound)

module.exports = router
